### PR TITLE
feat: support --dependency-tree 

### LINKED ISSUE #35: feat: support `--dependency-tree`
Trivy supports `--dependency-tree` flag:

```sh
--dependency-tree        [EXPERIMENTAL] show dependency origin tree of vulnerable packages
...

$ trivy image --dependency-tree alpine:3.14.
...
Dependency Origin Tree (Reversed)
=================================
alpine:3.14.1 (alpine 3.14.1)
├── busybox@1.33.1-r3, (UNKNOWN: 0, LOW: 0, MEDIUM: 2, HIGH: 10, CRITICAL: 0)
├── libcrypto1.1@1.1.1k-r0, (UNKNOWN: 0, LOW: 0, MEDIUM: 2, HIGH: 5, CRITICAL: 1)
├── libretls@3.3.3p1-r2, (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 1, CRITICAL: 0)
├── libssl1.1@1.1.1k-r0, (UNKNOWN: 0, LOW: 0, MEDIUM: 2, HIGH: 5, CRITICAL: 1)
├── ssl_client@1.33.1-r3, (UNKNOWN: 0, LOW: 0, MEDIUM: 2, HIGH: 10, CRITICAL: 0)
└── zlib@1.2.11-r3, (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 1, CRITICAL: 1)
```
`--dependency-tree` enables `--list-all-pkgs`, so we should release #34  at first

### PR DESCRIPTION
**Pull request by malikovmm**

### CODE REVIEW

**Review by afdesk — CHANGES_REQUESTED** [review]
we need to add the test cases for dependency tree

**Comment by malikovmm** [comment]
https://github.com/afdesk/scan2html/pull/32

**Comment by afdesk** [comment]
@malikovmm please, fix the confilcts at first. thanks

**Comment by nikpivkin** [comment]
@afdesk I tested the plugin with the --dependency-tree flag, everything is ok

**Comment by afdesk** [comment]
> @afdesk I tested the plugin with the --dependency-tree flag, everything is ok

@nikpivkin could you retest it again?

**Comment by nikpivkin** [comment]
@afdesk I tested it, everything works well

**Comment by afdesk** [comment]
great!
@malikovmm @nikpivkin thanks, guys!

**Pull request merged**
